// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdVyxllDPNGQPCsKEqqd33MNU6PcCYCKc',
    appId: '1:69338856224:web:b3bc9e2f509f3f823db545',
    messagingSenderId: '69338856224',
    projectId: 'hec-connect',
    authDomain: 'hec-connect.firebaseapp.com',
    storageBucket: 'hec-connect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwYYI2XESxcfufGzmlOPbOpbU1nwuEEFw',
    appId: '1:69338856224:android:9ad0bb6f8ccf330b3db545',
    messagingSenderId: '69338856224',
    projectId: 'hec-connect',
    storageBucket: 'hec-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtbPuI6WaAbX9MYNSUO1XL5MC0VD8bOQw',
    appId: '1:69338856224:ios:1b167af4584d34993db545',
    messagingSenderId: '69338856224',
    projectId: 'hec-connect',
    storageBucket: 'hec-connect.firebasestorage.app',
    iosClientId: '69338856224-9acin7o6rpt11u6g9v8urdo6ofskr642.apps.googleusercontent.com',
    iosBundleId: 'com.hecabidjan.hecConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtbPuI6WaAbX9MYNSUO1XL5MC0VD8bOQw',
    appId: '1:69338856224:ios:1b167af4584d34993db545',
    messagingSenderId: '69338856224',
    projectId: 'hec-connect',
    storageBucket: 'hec-connect.firebasestorage.app',
    iosClientId: '69338856224-9acin7o6rpt11u6g9v8urdo6ofskr642.apps.googleusercontent.com',
    iosBundleId: 'com.hecabidjan.hecConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdVyxllDPNGQPCsKEqqd33MNU6PcCYCKc',
    appId: '1:69338856224:web:1a00015934af24be3db545',
    messagingSenderId: '69338856224',
    projectId: 'hec-connect',
    authDomain: 'hec-connect.firebaseapp.com',
    storageBucket: 'hec-connect.firebasestorage.app',
  );

}